directories:
  output: dist_electron
  buildResources: assets
appId: CY
productName: CY-ZS
copyright: Copyright Â© 2021 xc
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
win:
  icon: electron/logo.ico
files:
  - filter:
      - dist/**/*
      - electron/**/*
electronVersion: 18.0.4
